# Practical AI Journey Website
location = /projects/practical-ai-journey {
    return 301 /projects/practical-ai-journey/;
}

location /projects/practical-ai-journey/ {
    rewrite ^/projects/practical-ai-journey(/.*)$ $1 break;
    proxy_pass http://127.0.0.1:8010;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Script-Name /projects/practical-ai-journey;

    proxy_redirect off;
}
